### PR TITLE
Adjusted forecasted wind speed based on wind measurement height. 

### PR DESCRIPTION
**Pull request by jbrekel**
## The What

Altered the forecast class to convert forecasted wind speed from u10 to u2. Then, the forecast class checks for a user-provided wind measurement height (z) and converts the forecasted wind speed from u2 to uz. 

I didn't run any of the tests because I don't think any of them use the forecast class. 

## The Why

Kendall noticed that the forecasted ETref values we were getting were pretty high. After some investigation, he realized that it is because the National Weather Service probably uses a wind measurement height of 10 meters, while the weather class wndht attribute was set to 2 meters. Since the wind measurement height was higher, forecasted wind speeds were higher. That led to inflated ETref values. 

We had a lot of discussion about the best way to fix this, and decided on this implementation. Since FAO-56 provides a way to convert uz to u2, we decided that it is probably best to convert the wind speed to u2 first, and then convert further if the rest of the user's wind data comes from a different height. 

Kendall also mentioned that it might be best to change the "Wndsp" column of Weather to "u2". I am a little concerned about preserving backwards compatibility with that change, but there might be a way to do that. I think you should discuss his thoughts on the structure of the wdata attribute. 

Tagging Kendall so that he can add any additional comments he sees fit @isukendall

### CODE REVIEW

**Comment by isukendall** [comment]
I would be happy to discuss reasoning for changing the "Wndsp" column to "u2". I believe it can be a little confusing to the user, and any others who might be using the Weather file output for comparisons, or for sharing datasets. In the end, to follow FAO-56 protocol we have to convert everything to 2m height, so why not just get it all there to be at the standardized height?

**Comment by kthorp** [comment]
Can you show both...similar to how ETref may be computed, but not required input.  Users may also get frustrated if they find their windspeed information has magically changed.
________________________________

**Comment by kthorp** [comment]
This is very complicated.  So far, the tool has required the user to provide uz and wind measurement height. Then it does the conversion to u2.  However, for a weather file with forecast data, I've been merging wind speed data from different sources.  AZMET has 3.0 m wind measurement height. Apparently, NDFD wind is estimated at 10 m, which I was unaware of and neglected to consider til today unfortunately.  This makes a case for having a wind measurement height paired with each wind speed datum, which seems redundant but necessary for full clarity. I don't know.  I don't particularly like forcing the user to input u2.  The tool should be smart enough to accommodate different wind measurement heights. I will have to think on the backward compatibility issue.  We should probably meet to discuss this one.

**Comment by kthorp** [comment]
After sleep, I better understand what this PR does...basically gives the user the option to adjust NDFD wind speed to a different measurement height.  That's a great addition and quite an oversight on my part.  Wish I could go back 5 years when I started working with this forecasting methodology.

As for the side discussion on converting everything to u2, I'm not sure about that.  The Weather class is designed for a user to input a Wndsp and a wndht, and the tool handles all the conversions to u2. I'd like to retain that functionality.  Giving user option to convert NDFD forecasted wind speeds from 10.0 to wndht in Weather should clear up the issues of having weather files with wind at different heights.

**Comment by jbrekel** [comment]
I am in complete agreement.

**Pull request merged**
