### PR TITLE
Single Crop Coefficient Option

### PR DESCRIPTION
**Pull request by tpokoski**
Starting this pull request now, but it definitely needs polishing and conversation on where it should lead. 
Purpose of this is to add the Single Crop Coefficient method for calculating ETc, presented in Chapter 6 of FAO-56. 

At the moment, 3 files are altered: parameters.py, model.py, and visualizations.py

### parameters.py
Added the option for users to input values for Kc initial, Kc mid, and Kc end. Typically taken from Table 12 of FAO-56.
The current default values were just for testing purposes, **_should be changed._** 

### model.py
This holds the most changes, the addition of a new Boolean parameter 'single', and following conditionals that will use inputs from the Parameters Class to calculate Kc using the Single Crop Coefficient equation 58. 

### visualizations.py
Changed the Kc graph to separate Kc and Kc_adj lines, and adding the respective Boolean parameters to the function.

As for the outputs, they weren't touched, but they probably should be altered, as many columns in the table aren't necessary for the single crop coefficient method. I feel like adding this might be a can of worms, there could be plenty more to add, or it could be kept simple.

### CODE REVIEW

**Comment by kthorp** [comment]
Tyler,

I see it's fairly straight-forward to get a Kc-based computation of ETc as you've shown here.  A question I have is what becomes of the latter parts of the simulation after Kc-based ETc is calculated. It would appear that the following calculations of Kcadj and ETcadj (etc) are basically meaningless outputs in this case and could lead to confusion.

For code design, would it be better to have the model just compute both the Kc-based ETc (reported as a separate output column) along with all the outputs for the dual-Kc method?  The only drawback is that it requires users to input crop coefficients for both the single and dual approach...although the way you have it programmed here, they would have to do that anyway.  Are we talking just two additional outputs...that is a Kc and an ETc for the single method? If so, I'd say let's program it so the model computes both concurrently. We would need to distinguish column names for Kc and ETc for the single-Kc approach.  What would be appropriate for that? @isukendall 

Kelly

**Comment by isukendall** [comment]
I agree that calculating both concurrently would be required and preferred. Unfortunately, there is no difference in the abbreviations used in FAO-56 or ASCE Manual 70, that I'm aware of.

Ideas for column names for single coefficient:

Kc          ETc
Kcc        ETcc
Kc_1     ETc_1
Kc1        ETc1
Kcsing  ETcsing
Kc_s      ETc_s

Open to other ideas. My preference would be Kc1 and ETc1.


Kendall DeJonge
Agricultural Engineer
USDA-ARS

Out of Office 7/19-7/25 Annual Leave (no response to email)
Out of Office 7/29-7/31 ASABE International Annual Meeting
USDA-ARS LIRF Field Day, Wednesday 8/7

**Comment by kthorp** [comment]
I also like Kc1 and ETc1.  Would it be appropriate to then use Kc2 and ETc2 for the dual approach?  Can Tyler work on updating the pull request?  Thanks!

**Comment by isukendall** [comment]
Using Kc2 and ETc2 could be an option. Or, if you consider the dual method as the default, you could keep them as-is. 

Tyler is out sick today and we have Field Day tomorrow, but he can work on it when things settle down.

**Comment by tpokoski** [comment]
Sorry for the delay! Here's my attempt at adding the changes discussed. 

### parameters.py
No additional changes, still need to decide the default values for Kcini, Kcmid, and Kcend

### model.py

- Removed the input variable 'single', as the Single Crop Coefficient method would be run concurrently to the Dual Crop Coefficient method. 
- Added variables Kc1 and ETc1

### visualization.py
- Added an input parameter to the _plot_Kc_ function for Kc1 (default=True)
- Added a 'blueviolet' line for the Kc1 to be graphed onto the figure

**Comment by kthorp** [comment]
This PR is merged with many additional edits from me, mainly to reorder columns in the output file, etc.  I decided to change the column headers for the dual approach Kc and ETc to 'Kc2' and 'ETc2', respectively.  This may affect workflows based on previous versions, but helps to distinguish the single and dual calculations, now made simultaneously during a model run with acceptance of this PR.

**Pull request merged**
