### PR TITLE
Fixed bug in model, added comments

### PR DESCRIPTION
**Pull request by jbrekel**
Fixed the bug in model that we discussed on 6/2/2023. Made the changes suggested by Kelly. 

Left comments around the equations of the bug. Still need to decide whether the tdew declaration line is a bug (because it uses the Tmin column of wdata). 

Also noticed an oversight in documentation regarding Kcadj. Fixed that. 

Let me know if you have questions.

### CODE REVIEW

**Comment by covix** [comment]
Hi! I was checking the same lines of code in these days, and I notice that in between of Eq. 63 and 64 of FAO 56 they state  that "Where dewpoint temperature or other hygrometric data are not available or are of questionable quality, RHmin can be estimated by substituting mean daily minimum air temperature, Tmin, for Tdew".

I am not sure on how to address this part in the code, but I guess that's where it came from, in the first place!

**Comment by jbrekel** [comment]
Hi Luca! 

Thanks for point that out! I see where they say that now. I bet you are right that this is where that came from. 

I am still a little stumped on how to address this part of the code. Just thinking out loud for a moment...
- If the variable is called "tdew", then it should probably access the Tdew column of wdata. 
- We need to guard against use cases in which Tdew is NaN. In these cases, Tmin should be used in place of Tdew. 
- We might need another conditional statement to determine whether the user has supplied data for Tdew. If they have that, RHmin should be estimated with that. Else, RHmin should be estimated with Tmin.

I'll probably take a couple minutes to update this pull request with a commit of what I am thinking here. 

Thanks again Luca. Pointing that out helped move the process along!

-Josh

**Comment by covix** [comment]
Hi Josh!

That looks like a quite good solution!
What do you think about adding also the reference to the equation number as a comment?

**Comment by jbrekel** [comment]
Hi Luca, 

Sorry for the delayed response! 

I think that is smart. I added references to equations 63 and 64 in that part of the code. 

Let me know if you think of any other additions to the package!

-Josh

**Comment by kthorp** [comment]
Upon further review, the thinking here was that if rhmin is missing, then there will likely also me no tdew, because weather stations typically estimate tdew from a measure of humidity.  So the original code made the jump to estimate tdew from tmin, and that was confusing everyone (even me).  I'll adopted some of the logic that Josh added.

**Pull request merged**
