### PR TITLE
Reworked SoilWater to Avoid Circularity Concern

### PR DESCRIPTION
**Pull request by jbrekel**
Reworked SoilWater to be dependent on Parameters and SoilProfile rather than Model. Consequently added root depth simulation capabilities to the class. Reworked all docstrings and tests to reflect these changes.

At this point, all of the edits requested in my most recent meeting with Kelly have been completed. It is again time to review the class to determine how close to final it is.

### CODE REVIEW

**Comment by kthorp** [comment]
I'm back to this PR.  I believe I have addressed and finalized everything else that Josh submitted, but unfortunately, we didn't get a chance to finalize the SoilWater class before he had to move on.  If possible, it would be good to meet to discuss the way forward.  Either me and @isukendall alone...or if @jbrekel has bandwidth and interest you are welcome to. I'm keen to finish this myself if necessary.  It would be a great milestone to be able to directly inject neutron SWC into the model.  Do you already have a functional workflow for this that you're using in 2023 growing season?  Also, I think if we finalize this SoilWater PR, we should have enough for a ver. 1.2.0 release and perhaps a SoftwareX paper.

**Comment by isukendall** [comment]
We do have a functional workflow to inject SWC into the model, among other things. We needed to get something together this summer that would work for our needs (or most of them) to replace our old water balance model, so there are several things we have developed that aren't in pyfao56. I think one assumption was that if something would be valuable to pyfao56, we could always go back and add it in.

I think it's a fair assumption that @jbrekel does not have the bandwidth right now, he's taken on more classes and last I counted he has 5 sections he's teaching at 2 different universities. 

I think it would be good for @kthorp and I to get together, and I can run you through our workflow, and get you access to our code if you want to take a look. My programming savvy isn't there to do it myself, but if you had the time, working code is already written. I think it would be great to get a couple more releases. I'm also working on a paper demonstrating the functionality of our code, which is largely wrapped around pyfao56. I'll send you the draft.

**Comment by kthorp** [comment]
I have completely overhauled the SoilWater class in effort to simplify it, improve understanding, and improve flexibility in the code.  Some main comments:
1. I have renamed the main class from SoilWater to SoilWaterSeries. Just today, it occurred to me that the class was designed to be limited to a single measurement location.  I finally understood this by realizing that the instances of par and sol had to be the same among all SWC measurements in a SoilWater set.  This means a single instance of SoilWater can handle data for only one location. I don't believe I understood this limitation of the class until now.  It is perhaps necessary to limit the class in this way, due to the complexity of the soil water data.  However, I have updated many comments and variable names to help with understanding this point.
2.  I have developed a new abstraction called SoilWaterProfile. It is a subclass of SoilWaterSeries. It handles data and computations for one soil water profile measurement event (e.g., neutron readings at one hole on one date). It contains methods for calculating Dr and Drmax (and other metrics) for the profile. A function is available to obtain Zr from a Model class, so root depths do not have to be recomputed. There is also no circularity concern, because the instance of Model disappears from scope after the function is called.  Users can also pass their own estimates of Zr to the class. The SoilWaterSeries class thus manages a time series of SoilWaterProfile classes with appropriate methods for printing, loading, saving, etc.
3. The previous effort assumed that soil profile layers and SWC measurement layers were identical, which is often not the case in practice.  I have increased the flexibility of the method to process the data considering possibility of different layer depths for soil profile and SWC data.
4. The previous effort also did not account for measured SWC above DUL. It appears measured SWC was capped at DUL, which prevents negative depletion calculations.  However, I believe this is a topic for further scientific discussion.  Should measured SWC above the DUL be accounted for in depletion calculations or not?  I have added flexibility using a "negdep" boolean input, so user can choose how to handle case of negative depletion (i.e., allow it or cap it at DUL). It would be a good scientific exercise to study how this impacts depletion calculations for measured SWC data.
5. I still have to develop a test for the new methods in SoilWaterSeries and SoilWaterProfile. Also, this will certainly break the LIRF workflow, so I hope we can work to integrate the next version of pyfao56 into your workflow.  @isukendall @jbrekel @tpokoski

**Comment by jbrekel** [comment]
I might be able to find an hour this semester to meet, but I am not sure how helpful I would be at said meeting...Five classes across two universities has thoroughly scrambled my brain, and it is week 1! Just let me know if you would like me to be present for the meeting and then we can communicate about the time to meet. 

I think these changes are interesting and I am glad you took on a substantial portion of the class redesign. Before leaving, I mentioned to Kendall and Tyler that I think the package needs a "Roots" class. That is the only design aspect (I would worry about) that I don't really see implemented here. You said you give users the chance to use their own estimates of Zr—why not just make a sleek class for controlling that sort of thing? It could be a utility class called by Model whenever Model requires Zr. In the Roots class, users could put their own estimates there so that their estimates go to both Model and the SoilWaterSeries classes. That also gives some flexibility to future design because you could add new methods to the Roots class for alternative ways to estimate Zr (I am sure there are other ways in the literature besides what FAO-56 specifies in Annex 8). I know estimates of Zr are probably both the most sensitive input to the model as well as the most uncertain aspect of the model. I think that is all the more reason to separate that aspect out into its own contained Module. However, perhaps that presents technical difficulties with any sensitivity analyses done down the line (I am not sure whether it does). 

Overall, I think these changes are all headed in the right direction and that they are smarter than anything I could have developed. I would just reemphasize tapping into the modularity of pyfao56 by adding a Root class.

**Pull request merged**
